# Generated by Django 3.1.6 on 2021-02-16 22:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='role',
            name='role_name',
            field=models.CharField(default='2021-02-16', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
