# Generated by Django 3.1.6 on 2021-02-16 23:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210216_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
