# Generated by Django 3.1.6 on 2021-03-09 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_auto_20210309_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='token',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='token_expiry',
        ),
        migrations.CreateModel(
            name='MailItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_addressed_to', models.CharField(max_length=64)),
                ('legal_entity_name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
                ('entry_date', models.DateField()),
                ('from_institution', models.CharField(max_length=64)),
                ('account_number', models.CharField(max_length=32)),
                ('document_date', models.DateField(auto_now_add=True)),
                ('CLD', models.CharField(max_length=32)),
                ('suffix', models.CharField(max_length=32)),
                ('tax_year', models.DateField()),
                ('file_path', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
