# Generated by Django 3.1.6 on 2021-03-13 23:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210309_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailitem',
            old_name='from_institution',
            new_name='institution',
        ),
        migrations.AlterField(
            model_name='mailitem',
            name='entry_date',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='mailitem',
            name='tax_year',
            field=models.IntegerField(),
        ),
    ]
