# Generated by Django 3.1.6 on 2021-03-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210311_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailitem',
            name='CLD',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='mailitem',
            name='suffix',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='mailitem',
            name='tax_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
