# Generated by Django 3.1.6 on 2021-03-14 18:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210313_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailitem',
            old_name='CLD',
            new_name='cld',
        ),
        migrations.AlterField(
            model_name='mailitem',
            name='entry_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
